In [2]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import seaborn as sns
import torch

In [3]:
data_path = "/home/steffi/dev/master_thesis/hiding_adversarial_attacks/data/external"
mnist_path = os.path.join(data_path, "MNIST/processed")
fashion_mnist_path = os.path.join(data_path, "FashionMNIST/processed")
cifar10_path = os.path.join(data_path, "CIFAR10")

## DeepFool
adversarial_path = "/home/steffi/dev/master_thesis/hiding_adversarial_attacks/data/preprocessed/adversarial"
mnist_adv_path = os.path.join(adversarial_path, "data-set=MNIST--attack=DeepFool--eps=0.2--cp-run=HAA-946")
fashion_mnist_adv_path = os.path.join(adversarial_path, "data-set=FashionMNIST--attack=DeepFool--eps=0.105--cp-run=HAA-952")
cifar10_adv_path = os.path.join(adversarial_path, "data-set=CIFAR10--attack=DeepFool--eps=0.1--cp-run=HAA-943")

# Load data

In [9]:
def load_confidences(data_set_path: str):
    train_confidences_orig, train_labels_orig = torch.load(os.path.join(data_set_path, "confidences_orig.pt"))
    train_confidences_adv, train_labels_adv = torch.load(os.path.join(data_set_path, "confidences_adv.pt"))
    return train_confidences_orig, train_labels_orig, train_confidences_adv, train_labels_adv

In [10]:
# Confidences
mnist_train_confidences_orig, mnist_train_labels_orig, mnist_train_confidences_adv, mnist_train_labels_adv = load_confidences(mnist_adv_path)
fashion_mnist_train_confidences_orig, fashion_mnist_train_labels_orig, fashion_mnist_train_confidences_adv, fashion_mnist_train_labels_adv = load_confidences(fashion_mnist_adv_path)
cifar10_train_confidences_orig, cifar10_train_labels_orig, cifar10_train_confidences_adv, cifar10_train_labels_adv = load_confidences(cifar10_adv_path)

In [11]:
df_mnist_train_labels_orig = pd.DataFrame(mnist_train_labels_orig.numpy())
df_mnist_train_labels_adv = pd.DataFrame(mnist_train_labels_adv.numpy())

df_fashion_mnist_train_labels_orig = pd.DataFrame(fashion_mnist_train_labels_orig.numpy())
df_fashion_mnist_train_labels_adv = pd.DataFrame(fashion_mnist_train_labels_adv.numpy())

df_cifar10_train_labels_orig = pd.DataFrame(cifar10_train_labels_orig.numpy())
df_cifar10_train_labels_adv = pd.DataFrame(cifar10_train_labels_adv.numpy())

In [12]:
def get_top_k_df(confidences):
    val, idcs = torch.topk(confidences, k=2, dim=1)
    df = pd.DataFrame([idcs[:,0].numpy(), val[:,0].numpy(),idcs[:,1].numpy(), val[:,1].numpy()], index=["top_1_idx", "top_1_conf", "top_2_idx", "top_2_conf"]).T
    return df

In [13]:
top_k_mnist_train_orig = get_top_k_df(mnist_train_confidences_orig)
top_k_fashion_mnist_train_orig = get_top_k_df(fashion_mnist_train_confidences_orig)
top_k_cifar10_train_orig = get_top_k_df(cifar10_train_confidences_orig)

top_k_mnist_train_adv = get_top_k_df(mnist_train_confidences_adv)
top_k_fashion_mnist_train_adv = get_top_k_df(fashion_mnist_train_confidences_adv)
top_k_cifar10_train_adv = get_top_k_df(cifar10_train_confidences_adv)



In [15]:
top_k_mnist_train_orig.sort_values(by="top_1_conf", ascending=True)

top_1_idx  top_1_conf  top_2_idx    top_2_conf
46477        4.0    0.376817        1.0  3.555147e-01
51569        6.0    0.403857        9.0  3.892199e-01
44733        5.0    0.408511        9.0  3.955659e-01
11081        0.0    0.426630        5.0  3.684263e-01
11952        2.0    0.443506        1.0  2.238729e-01
...          ...         ...        ...           ...
45562        7.0    1.000000        3.0  1.581030e-08
26070        9.0    1.000000        4.0  5.507641e-08
26065        7.0    1.000000        9.0  5.127414e-08
45593        8.0    1.000000        6.0  2.895378e-08
26147        8.0    1.000000        5.0  2.900429e-09

[52295 rows x 4 columns]

In [112]:
top_k_mnist_train_adv.head()

top_1_idx  top_1_conf  top_2_idx  top_2_conf
0        7.0    0.474560        9.0    0.424590
1        5.0    0.689440        3.0    0.283222
2        9.0    0.611947        8.0    0.382149
3        7.0    0.543428        2.0    0.448588
4        4.0    0.580193        9.0    0.410955

In [100]:
top_k_cifar10_train_orig.head()

top_1_idx  top_1_conf  top_2_idx  top_2_conf
0        3.0    0.884584        5.0    0.038046
1        3.0    0.763706        0.0    0.065399
2        0.0    0.630749        3.0    0.204524
3        3.0    0.781105        5.0    0.133733
4        3.0    0.599040        0.0    0.090341

In [107]:
top_k_cifar10_train_orig.head()

top_1_idx  top_1_conf  top_2_idx  top_2_conf
0        3.0    0.884584        5.0    0.038046
1        3.0    0.763706        0.0    0.065399
2        0.0    0.630749        3.0    0.204524
3        3.0    0.781105        5.0    0.133733
4        3.0    0.599040        0.0    0.090341

In [108]:
top_k_cifar10_train_adv.head()

top_1_idx  top_1_conf  top_2_idx  top_2_conf
0        3.0    0.809320        4.0    0.068449
1        3.0    0.873839        6.0    0.034610
2        0.0    0.568806        3.0    0.252050
3        3.0    0.743912        5.0    0.161988
4        3.0    0.598399        5.0    0.090844

In [54]:
d = pd.DataFrame(mnist_train_confidences_orig.numpy())

In [67]:
val, idcs = torch.topk(mnist_train_confidences_orig, k=2, dim=1)

In [81]:
idcs

tensor([[7, 9],
        [5, 3],
        [9, 8],
        ...,
        [4, 9],
        [9, 4],
        [9, 4]])

In [80]:
idcs[:,0]

tensor([7, 5, 9,  ..., 4, 9, 9])

In [92]:
df = pd.DataFrame([idcs[:,0].numpy(), val[:,0].numpy(),idcs[:,1].numpy(), val[:,1].numpy()], index=["top_1_idx", "top_1_conf", "top_2_idx", "top_2_conf"]).T

In [93]:
df.head()

top_1_idx  top_1_conf  top_2_idx    top_2_conf
0        7.0    1.000000        9.0  7.216924e-08
1        5.0    0.984226        3.0  1.147289e-02
2        9.0    0.999952        8.0  4.078618e-05
3        7.0    0.999750        2.0  1.813207e-04
4        4.0    1.000000        9.0  4.286920e-07

In [62]:
largest_indcs = d.T.nlargest(n=2, columns=range(0, d.shape[0])).index

In [63]:
largest_indcs

Int64Index([7, 9], dtype='int64')

In [64]:
d.T.loc[largest_indcs]

0         1         2         3             4             5      \
7  9.999999e-01  0.000002  0.000001  0.999750  6.488721e-08  1.000000e+00   
9  7.216924e-08  0.000157  0.999952  0.000011  4.286920e-07  1.866005e-08   

          6             7             8             9      ...         52285  \
7  8.847245e-17  2.825724e-12  6.712441e-12  2.200307e-15  ...  7.581013e-10   
9  3.856242e-08  7.875891e-08  1.239593e-10  1.182660e-09  ...  1.000000e+00   

          52286         52287         52288         52289     52290  \
7  1.465759e-08  1.893714e-08  1.018177e-09  3.269034e-14  0.000036   
9  1.000000e+00  1.000000e+00  9.999998e-01  3.464417e-11  0.997996   

          52291     52292         52293         52294  
7  1.460610e-12  0.000003  1.647018e-07  5.196413e-07  
9  1.519156e-07  0.000020  9.999893e-01  9.999928e-01  

[2 rows x 52295 columns]

In [56]:
d.idxmax(axis=1)

0        7
1        5
2        9
3        7
4        4
        ..
52290    9
52291    5
52292    4
52293    9
52294    9
Length: 52295, dtype: int64

In [47]:
mnist_train_label_orig.numpy()

array([7, 5, 9, ..., 4, 9, 9])

In [48]:
np.sum(mnist_train_label_orig.numpy() == mnist_train_confidences_orig.numpy().argmax(axis=1))

52282

In [39]:
df_mnist_train = pd.DataFrame(mnist_train_confidences_orig.numpy())

In [42]:
df_mnist_train.idxmax(axis=1)

0        7
1        5
2        9
3        7
4        4
        ..
52290    9
52291    5
52292    4
52293    9
52294    9
Length: 52295, dtype: int64

## Why are the correctly classified counts so low??

In [20]:
np.sum(mnist_train_confidences_orig.numpy().argmax(axis=1) == mnist_train_labels_orig.numpy())

5413

In [21]:
np.sum(fashion_mnist_train_confidences_orig.numpy().argmax(axis=1) == fashion_mnist_train_labels_orig.numpy())

5299

In [22]:
np.sum(cifar10_train_confidences_orig.numpy().argmax(axis=1) == cifar10_train_labels_orig.numpy())

4868

In [11]:
df_mnist_train_conf = pd.DataFrame(mnist_train_confidences_orig.numpy())

In [12]:
df_mnist_train_conf.head()

0             1             2             3             4  \
0  9.106839e-09  9.999980e-01  1.332047e-07  1.145887e-08  1.027700e-06   
1  6.883028e-10  9.999979e-01  3.241036e-09  3.283960e-09  5.851322e-07   
2  1.277275e-09  1.552069e-11  1.000000e+00  1.346936e-08  1.737813e-15   
3  6.199202e-12  2.906035e-11  1.547877e-10  4.497145e-11  2.525052e-12   
4  2.112273e-11  3.375414e-12  1.911869e-10  2.981154e-10  5.153938e-11   

              5             6             7             8             9  
0  4.720181e-08  2.063075e-07  4.926950e-07  2.166244e-08  7.077777e-09  
1  5.883354e-08  1.400277e-08  1.519055e-06  4.152741e-08  8.983880e-09  
2  5.993823e-15  6.450398e-14  3.547708e-08  1.412896e-08  5.272634e-13  
3  2.840564e-11  1.815046e-12  1.950423e-13  1.000000e+00  2.137064e-09  
4  6.121966e-09  4.378193e-09  2.559471e-14  1.000000e+00  1.215892e-08

In [22]:
pred_labels = df_mnist_train_conf.idxmax(axis=1).to_numpy()

In [39]:
df_mnist_train_labels

0
0      6.0
1      7.0
2      6.0
3      9.0
4      4.0
...    ...
52290  2.0
52291  1.0
52292  4.0
52293  4.0
52294  2.0

[52295 rows x 1 columns]

In [40]:
pred_labels

array([4, 4, 1, ..., 3, 5, 5])

# Q1: How is the distribution of classes in the data sets?

## MNIST

### Original

## FashionMNIST

## Labels mappings:
* 0	T-shirt/top
* 1	Trouser
* 2	Pullover
* 3	Dress
* 4	Coat
* 5	Sandal
* 6	Shirt
* 7	Sneaker
* 8	Bag
* 9	Ankle boot

### Original

### Adversarial

## CIFAR10

Label mappings:
* 0	Airplane
* 1	Car
* 2	Bird
* 3	Cat
* 4	Deer
* 5	Dog
* 6	Frog
* 7	Horse
* 8	Ship
* 9	Truck

### Original

### Adversarial